import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { addApolloState, initializeApollo } from '../lib/apolloClient';
import { gql, useQuery } from '@apollo/client';
import ProductCard from '../components/product/ProductCard';

const GET_PRODUCTS = gql`
  query {
    products {
      id
      slug
      name
      images {
        formats
      }
    }
  }
`;

const Home = () => {
  const { data } = useQuery(GET_PRODUCTS);
  const products = data ? data.products : null;

  return (
    <div className="container">
      <Head>
        <title>ECommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className="card-grid">
          {products.map((prod) => (
            <ProductCard key={prod.id} product={prod} />
          ))}
        </div>
      </section>
    </div>
  );
};

export const getStaticProps = async () => {
  const apolloClient = initializeApollo();

  await apolloClient.query({
    query: GET_PRODUCTS,
  });

  return addApolloState(apolloClient, {
    props: {},
  });
};

export default Home;
